//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S2G5_PVFAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supply
    {
        public int VendorId { get; set; }
        public int MaterialId { get; set; }
        public string SupplyUnitPrice { get; set; }
    
        public virtual RawMaterial RawMaterial { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
